// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/docs/theming
//
// Provides React context for runtime theme switching.
// Wrap any subtree in <PdfxThemeProvider theme={myTheme}> to override the active theme.

/* eslint-disable react-refresh/only-export-components */
/* eslint-disable react-hooks/rules-of-hooks */

import { type DependencyList, type ReactNode, createContext, useContext, useMemo } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = useMemo(() => theme ?? defaultTheme, [theme]);
  return <PdfxThemeContext.Provider value={resolvedTheme}>{children}</PdfxThemeContext.Provider>;
}

export function usePdfxTheme(): PdfxTheme {
  try {
    return useContext(PdfxThemeContext);
  } catch (error) {
    if (
      error instanceof Error &&
      /invalid hook call|useContext|cannot read properties of null/i.test(error.message)
    ) {
      return defaultTheme;
    }
    throw error;
  }
}

export function useSafeMemo<T>(factory: () => T, deps: DependencyList): T {
  try {
    return useMemo(factory, deps);
  } catch (error) {
    if (
      error instanceof Error &&
      /invalid hook call|useMemo|cannot read properties of null/i.test(error.message)
    ) {
      return factory();
    }
    throw error;
  }
}
