// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/docs/theming
//
// All PDF components import this file for their styling tokens.
// Edit the values below to change the look of every component at once.

// ─── Theme Type ─────────────────────────────────────────────────────

interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: { none: number; sm: number; md: number; lg: number; full: number };
    letterSpacing: { tight: number; normal: number; wide: number; wider: number };
  };
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  page: {
    size: 'A4' | 'LETTER' | 'LEGAL';
    orientation: 'portrait' | 'landscape';
  };
}

// ─── Your Theme ─────────────────────────────────────────────────────

export const theme: PdfxTheme = {
  name: 'professional',

  primitives: {
    typography: {
      xs: 7,
      sm: 8,
      base: 9,
      lg: 10,
      xl: 12,
      '2xl': 14,
      '3xl': 16,
    },
    spacing: {
      0: 0,
      0.5: 1,
      1: 2,
      2: 4,
      3: 6,
      4: 8,
      5: 10,
      6: 12,
      8: 16,
      10: 20,
      12: 24,
      16: 32,
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeights: {
      tight: 1.1,
      normal: 1.25,
      relaxed: 1.35,
    },
    borderRadius: {
      none: 0,
      sm: 2,
      md: 4,
      lg: 8,
      full: 9999,
    },
    letterSpacing: {
      tight: -0.025,
      normal: 0,
      wide: 0.025,
      wider: 0.05,
    },
  },

  colors: {
    foreground: '#18181b',
    background: '#ffffff',
    muted: '#f4f4f5',
    mutedForeground: '#71717a',
    primary: '#18181b',
    primaryForeground: '#ffffff',
    border: '#e4e4e7',
    accent: '#3b82f6',
    destructive: '#dc2626',
    success: '#16a34a',
    warning: '#d97706',
    info: '#0ea5e9',
  },

  typography: {
    body: {
      fontFamily: 'Helvetica',
      fontSize: 9,
      lineHeight: 1.3,
    },
    heading: {
      fontFamily: 'Helvetica-Bold',
      fontWeight: 700,
      lineHeight: 1.15,
      fontSize: {
        h1: 16,
        h2: 12,
        h3: 10,
        h4: 9,
        h5: 8.5,
        h6: 8,
      },
    },
  },

  spacing: {
    page: {
      marginTop: 28,
      marginRight: 30,
      marginBottom: 28,
      marginLeft: 30,
    },
    sectionGap: 6,
    paragraphGap: 2,
    componentGap: 4,
  },

  page: {
    size: 'A4',
    orientation: 'portrait',
  },
};
